[platformio]
description = My first classic size Micromouse robot.
default_envs = mouse_debug

[env]
platform = ch32v
board = genericCH32V103C8T6
monitor_speed = 115200
framework = noneos-sdk
build_flags = -I./include -DSYSCLK_FREQ_72MHz_HSI -DFIRMWARE_VERSION=\"v0.0.9\"
check_skip_packages = yes
check_severity = medium, high
check_src_filters =
    include/*
    src/*
    tests/*
    lib/*

[env:mouse_debug]
build_type = debug
build_unflags = -Os
build_flags = ${env.build_flags} -g -O0
test_testing_command =
    echo
    dummy

[env:mouse_release]
build_type = release
build_flags = ${env.build_flags} -Os
test_testing_command =
    echo
    dummy

[env:desktop]
platform = native
framework =
build_type = test
build_flags = -DDESKTOP_TEST
test_filter = desktop/*
